type               = "offchainreporting"
schemaVersion      = 1
contractAddress    = "0x6FCb4b66E23A39A5723B21A084B671b8c40bd136"
p2pPeerID          = "12D3KooWDLThzujR4NMxBcp8Q3PhRmS2RhZtGB4dLWKR4zrCLr4C"
p2pBootstrapPeers  = [
     "/dns4/chainlink-node-1/tcp/6690/p2p/12D3KooWBLub2stbaEnzUeQ1Van3h5HVzahY9LFYBkVgH4VNSbhb"  
]
isBootstrapPeer    = false
keyBundleID        = ""
monitoringEndpoint = "chain.link:4321"
transmitterAddress = "0x73c3290F588B29dd354922c4cecfd4f3D177C218"
observationTimeout = "10s"
blockchainTimeout  = "20s"
contractConfigTrackerSubscribeInterval = "2m"
contractConfigTrackerPollInterval = "1m"
contractConfigConfirmations = 3
observationSource = """
    fetch    [type=http method=POST url="http://external-adapter:6644" requestData="{}"];
    parse    [type=jsonparse path="data,result"];    
    fetch -> parse;
"""