blockchainTimeout = "20s"
contractAddress = "0xD4988baC598e872F326fBEDab223E7B8cA3CEe95"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m"
contractConfigTrackerSubscribeInterval = "2m"
isBootstrapPeer = false
keyBundleID = "f3d907c189dcee850f70cfc72d6c1d25a223c60fa8b1b49dc836af788296fc99"
monitoringEndpoint = "chain.link:4321"
observationSource = "    fetch    [type=http method=POST url=\"http://external-adapter:6644\" requestData=\"{}\"];\n    parse    [type=jsonparse path=\"data,result\"];    \n    fetch -> parse;\n"
observationTimeout = "10s"
p2pBootstrapPeers = ["/dns4/chainlink-node-1/tcp/6690/p2p/12D3KooWBLub2stbaEnzUeQ1Van3h5HVzahY9LFYBkVgH4VNSbhb"]
p2pPeerID = "12D3KooWPei4aMsM41wfRzA334bAZYRmLhmd9aRCGzRrjHcaZzDt"
schemaVersion = 1
transmitterAddress = "0xCEB1707AcbeE52bCE1F36cA2780148E38AB6a085"
type = "offchainreporting"
