blockchainTimeout = "20s"
contractAddress = "0x6FCb4b66E23A39A5723B21A084B671b8c40bd136"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m"
contractConfigTrackerSubscribeInterval = "2m"
isBootstrapPeer = false
keyBundleID = "537d250c74356df0ea05d23c03114b26a540052e9662376dfe1a65c68cdd8dbe"
monitoringEndpoint = "chain.link:4321"
observationSource = "    fetch    [type=http method=POST url=\"http://external-adapter:6644\" requestData=\"{}\"];\n    parse    [type=jsonparse path=\"data,result\"];    \n    fetch -> parse;\n"
observationTimeout = "10s"
p2pBootstrapPeers = ["/dns4/chainlink-node-1/tcp/6690/p2p/12D3KooWBLub2stbaEnzUeQ1Van3h5HVzahY9LFYBkVgH4VNSbhb"]
p2pPeerID = "12D3KooWH2KZG52vJ1vdgHGRdGXo1aQaHBNtHaWNtZKmeghuhJbD"
schemaVersion = 1
transmitterAddress = "0x41281755F432CfB23B7116A57383FF540eb60e46"
type = "offchainreporting"
