blockchainTimeout = "20s"
contractAddress = "0xD4988baC598e872F326fBEDab223E7B8cA3CEe95"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m"
contractConfigTrackerSubscribeInterval = "2m"
isBootstrapPeer = false
keyBundleID = "09e5cfe5ca760174e9dc02881cce5d5c04f7f6aed1198d7382e7cc97aee89614"
monitoringEndpoint = "chain.link:4321"
observationSource = "    fetch    [type=http method=POST url=\"http://external-adapter:6644\" requestData=\"{}\"];\n    parse    [type=jsonparse path=\"data,result\"];    \n    fetch -> parse;\n"
observationTimeout = "10s"
p2pBootstrapPeers = ["/dns4/chainlink-node-1/tcp/6690/p2p/12D3KooWBLub2stbaEnzUeQ1Van3h5HVzahY9LFYBkVgH4VNSbhb"]
p2pPeerID = "12D3KooWFWyDRbiFtySqfX4EA9HMQ9tmwRHzZqzCZbGZBP985FRi"
schemaVersion = 1
transmitterAddress = "0x3700858f9CD90C161ab03E6e9f57f04C0Ce24AbF"
type = "offchainreporting"
