blockchainTimeout = "20s"
contractAddress = "0xD4988baC598e872F326fBEDab223E7B8cA3CEe95"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m"
contractConfigTrackerSubscribeInterval = "2m"
isBootstrapPeer = true
p2pBootstrapPeers = []
p2pPeerID = "12D3KooWBLub2stbaEnzUeQ1Van3h5HVzahY9LFYBkVgH4VNSbhb"
schemaVersion = 1
type = "offchainreporting"
