version: '3.5'

services:
  node:
    container_name: chainlink-node
    image: chainlink-dev
    build:
      context: ../../
      dockerfile: core/chainlink.Dockerfile
    command: node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always
    depends_on:
      - node-db
    environment:
      - DATABASE_URL=postgresql://postgres:$CHAINLINK_PGPASSWORD@node-db:5432/$CHAINLINK_DB_NAME?sslmode=disable
      - LOG_LEVEL=info
    env_file:
      - chainlink-variables.env
    ports:
      - 6711:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
  node-2:
    depends_on:
      - node-db-2
    container_name: chainlink-node-2
    image: chainlink-dev
    build:
      context: ../../
      dockerfile: core/chainlink.Dockerfile
    command: node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always    
    environment:      
      - DATABASE_URL=postgresql://postgres:$CHAINLINK_PGPASSWORD@node-db-2:5432/$CHAINLINK_DB_NAME?sslmode=disable
      - LOG_LEVEL=info
    env_file:
      - chainlink-variables.env
    ports:
      - 6722:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
  node-3:
    depends_on:
      - node-db-3
    container_name: chainlink-node-3
    image: chainlink-dev
    build:
      context: ../../
      dockerfile: core/chainlink.Dockerfile
    command: node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always    
    environment:
      - DATABASE_URL=postgresql://postgres:$CHAINLINK_PGPASSWORD@node-db-3:5432/$CHAINLINK_DB_NAME?sslmode=disable
      - LOG_LEVEL=info
    env_file:
      - chainlink-variables.env
    ports:
      - 6733:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
  node-4:
    depends_on:
      - node-db-4
    container_name: chainlink-node-4
    image: chainlink-dev
    build:
      context: ../../
      dockerfile: core/chainlink.Dockerfile
    command: node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always    
    environment:
      - DATABASE_URL=postgresql://postgres:$CHAINLINK_PGPASSWORD@node-db-4:5432/$CHAINLINK_DB_NAME?sslmode=disable
      - LOG_LEVEL=info
    env_file:
      - chainlink-variables.env
    ports:
      - 6744:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
  
  node-db:
    container_name: chainlink-db
    image: postgres:11.6
    volumes:
      - node-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $CHAINLINK_DB_NAME
      POSTGRES_PASSWORD: $CHAINLINK_PGPASSWORD
    ports:
      - 5432:5432
  node-db-2:
    container_name: chainlink-db-2
    image: postgres:11.6
    volumes:
      - node-db-2-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $CHAINLINK_DB_NAME
      POSTGRES_PASSWORD: $CHAINLINK_PGPASSWORD
  node-db-3:
    container_name: chainlink-db-3
    image: postgres:11.6
    volumes:
      - node-db-3-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $CHAINLINK_DB_NAME
      POSTGRES_PASSWORD: $CHAINLINK_PGPASSWORD
  node-db-4:
    container_name: chainlink-db-4
    image: postgres:11.6
    volumes:
      - node-db-4-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $CHAINLINK_DB_NAME
      POSTGRES_PASSWORD: $CHAINLINK_PGPASSWORD
  
secrets:
  node_password:
    file: ../clroot/password.txt
  apicredentials:
    file: ../clroot/apicredentials
  keystore:
    file: ../secrets/0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6.json
volumes:
  node-db-data:
  node-db-2-data:
  node-db-3-data:
  node-db-4-data:

  
